/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javainterview;

import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class Question2_ClosestPrimeTest {

    private Question2_ClosestPrime underTest = new Question2_ClosestPrime();

    @Test public void testWithAPrime_Two() {
        assertEquals("Closest prime to 2 should be 2", underTest.findClosestPrimeTo(2), Integer.valueOf(2));
    }
    @Test public void testWithAPrime_Three() {
        assertEquals("Closest prime to 3 should be 3", underTest.findClosestPrimeTo(3), Integer.valueOf(3));
    }
    @Test public void testWithANonPrime_Four() {
        assertEquals("Closest prime to 4 should be 3 as we should pick lowest", underTest.findClosestPrimeTo(4), Integer.valueOf(3));
    }
    @Test public void testWithANonPrime_Fifteen() {
        assertEquals("Closest prime to 15 should be 13 as we pick lowest", underTest.findClosestPrimeTo(15), Integer.valueOf(13));
    }
    @Test public void testWithANonPrime_SixtyFive() {
        assertEquals("Closest prime to 65 should be 67", underTest.findClosestPrimeTo(65), Integer.valueOf(67));
    }

    //add any additional tests you feel are appropriate
}
