/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javainterview;

/** A simple app to prove the development environment is setup correctly */
public class HelloWorldApp {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new HelloWorldApp().getGreeting());
    }
}
